webapp/src/DOMJudgeBundle/Entity/Language.php
<?php declare(strict_types=1);
namespace DOMJudgeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use DOMJudgeBundle\Validator\Constraints\Identifier;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Programming languages in which teams can submit solutions
 * @ORM\Entity()
 * @ORM\Table(name="language", options={"collate"="utf8mb4_unicode_ci", "charset"="utf8mb4"})
 * @UniqueEntity("langid")
 * @UniqueEntity("externalid")
 */
class Language extends BaseApiEntity
{

    /**
     * @var string
     * @ORM\Id
     * @ORM\Column(type="string", name="langid", length=32, options={"comment"="Unique ID (string)"}, nullable=false)
     * @Serializer\Exclude()
     * @Assert\NotBlank()
     * @Assert\NotEqualTo("add")
     * @Identifier()
     */
    protected $langid;

    /**
     * @var string
     * @ORM\Column(type="string", name="externalid", length=255, nullable=true)
     * @Serializer\SerializedName("id")
     * @Serializer\Groups({"Default", "Nonstrict"})
     */
    protected $externalid;

    /**
     * @var string
     * @ORM\Column(type="string", name="name", length=255, options={"comment"="Descriptive language name"}, nullable=false)
     * @Serializer\Groups({"Default", "Nonstrict"})
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var string[]
     * @ORM\Column(type="json_array", length=4294967295, name="extensions", options={"comment"="List of recognized extensions (JSON encoded)"}, nullable=false)
     * @Serializer\Groups({"Nonstrict"})
     * @Serializer\Type("array<string>")
     * @Assert\NotBlank()
     */
    private $extensions;

    /**
     * @var boolean
     * @ORM\Column(type="boolean", name="allow_submit", options={"comment"="Are submissions accepted in this language?"}, nullable=false)
     * @Serializer\Exclude()
     */
    private $allowSubmit = true;

    /**
     * @var boolean
     * @ORM\Column(type="boolean", name="allow_judge", options={"comment"="Are submissions in this language judged?"}, nullable=false)
     * @Serializer\Groups({"Nonstrict"})
     */
    private $allowJudge = true;

    /**
     * @var double
     * @ORM\Column(type="float", name="time_factor", options={"comment"="Language-specific factor multiplied by problem run times"}, nullable=false)
     * @Serializer\Type("double")
     * @Serializer\Groups({"Nonstrict"})
     * @Assert\GreaterThan(0)
     * @Assert\NotBlank()
     */
    private $timeFactor = 1;

    /**
     * @var string
     * @ORM\Column(type="string", name="compile_script", length=32, options={"comment"="Script to compile source code for this language"}, nullable=true)
     * @Serializer\Exclude()
     */
    private $compile_script;

    /**
     * @var bool
     * @ORM\Column(type="boolean", name="require_entry_point", options={"comment"="Whether submissions require a code entry point to be specified."}, nullable=false)
     * @Serializer\Groups({"Nonstrict"})
     */
    private $require_entry_point = false;

    /**
     * @var integer
     *
     * @ORM\Column(name="require_loc", type="integer", nullable=true)
     */
    private $requireLoc = '0';

    /**
     * @var string
     * @ORM\Column(type="string", name="entry_point_description", options={"comment"="The description used in the UI for the entry point field."}, nullable=true)
     * @Serializer\Groups({"Nonstrict"})
     */
    private $entry_point_description;

    /**
     * @ORM\ManyToOne(targetEntity="Executable", inversedBy="languages")
     * @ORM\JoinColumn(name="compile_script", referencedColumnName="execid")
     * @Serializer\Exclude()
     */
    private $compile_executable;

    /**
     * @ORM\OneToMany(targetEntity="Submission", mappedBy="language")
     * @Serializer\Exclude()
     */
    private $submissions;

    /**
     * Set langid
     *
     * @param string $langid
     *
     * @return Language
     */
    public function setLangid($langid)
    {
        $this->langid = $langid;

        return $this;
    }

    /**
     * Get langid
     *
     * @return string
     */
    public function getLangid()
    {
        return $this->langid;
    }

    /**
     * Set externalid
     *
     * @param string externalid
     *
     * @return Language
     */
    public function setExternalid(string $externalid)
    {
        $this->externalid = $externalid;

        return $this;
    }

    /**
     * Get externalid
     *
     * @return string
     */
    public function getExternalid()
    {
        return $this->externalid;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Language
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set extensions
     *
     * @param string[] $extensions
     *
     * @return Language
     */
    public function setExtensions(array $extensions)
    {
        $this->extensions = $extensions;

        return $this;
    }

    /**
     * Get extensions
     *
     * @return string[]
     */
    public function getExtensions()
    {
        return $this->extensions;
    }

    /**
     * Set allowSubmit
     *
     * @param boolean $allowSubmit
     *
     * @return Language
     */
    public function setAllowSubmit($allowSubmit)
    {
        $this->allowSubmit = $allowSubmit;

        return $this;
    }

    /**
     * Get allowSubmit
     *
     * @return boolean
     */
    public function getAllowSubmit()
    {
        return $this->allowSubmit;
    }

    /**
     * Set allowJudge
     *
     * @param boolean $allowJudge
     *
     * @return Language
     */
    public function setAllowJudge($allowJudge)
    {
        $this->allowJudge = $allowJudge;

        return $this;
    }

    /**
     * Get allowJudge
     *
     * @return boolean
     */
    public function getAllowJudge()
    {
        return $this->allowJudge;
    }

    /**
     * Set timeFactor
     *
     * @param float $timeFactor
     *
     * @return Language
     */
    public function setTimeFactor($timeFactor)
    {
        $this->timeFactor = $timeFactor;

        return $this;
    }

    /**
     * Get timeFactor
     *
     * @return float
     */
    public function getTimeFactor()
    {
        return $this->timeFactor;
    }

    /**
     * Set compileScript
     *
     * @param string $compileScript
     *
     * @return Language
     */
    public function setCompileScript($compileScript)
    {
        $this->compile_script = $compileScript;

        return $this;
    }

    /**
     * Get compileScript
     *
     * @return string
     */
    public function getCompileScript()
    {
        return $this->compile_script;
    }

    /**
     * Set requireEntryPoint
     *
     * @param boolean $requireEntryPoint
     *
     * @return Language
     */
    public function setRequireEntryPoint($requireEntryPoint)
    {
        $this->require_entry_point = $requireEntryPoint;

        return $this;
    }

    /**
     * Get requireEntryPoint
     *
     * @return boolean
     */
    public function getRequireEntryPoint()
    {
        return $this->require_entry_point;
    }

    /**
     * Set entryPointDescription
     *
     * @param string $entryPointDescription
     *
     * @return Language
     */
    public function setEntryPointDescription($entryPointDescription)
    {
        $this->entry_point_description = $entryPointDescription;

        return $this;
    }

    /**
     * Get entryPointDescription
     *
     * @return string
     */
    public function getEntryPointDescription()
    {
        return $this->entry_point_description;
    }

    /**
     * Set requireLoc
     *
     * @param integer $requireLoc
     *
     * @return Language
     */
    public function setRequireLoc($requireLoc)
    {
        $this->requireLoc = $requireLoc;

        return $this;
    }

    /**
     * Get requireLocs
     *
     * @return integer
     */
    public function getRequireLoc()
    {
        return $this->requireLoc;
    }

    /**
     * Set compileExecutable
     *
     * @param \DOMJudgeBundle\Entity\Executable $compileExecutable
     *
     * @return Language
     */
    public function setCompileExecutable(\DOMJudgeBundle\Entity\Executable $compileExecutable = null)
    {
        $this->compile_executable = $compileExecutable;

        return $this;
    }

    /**
     * Get compileExecutable
     *
     * @return \DOMJudgeBundle\Entity\Executable
     */
    public function getCompileExecutable()
    {
        return $this->compile_executable;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->submissions = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add submission
     *
     * @param \DOMJudgeBundle\Entity\Submission $submission
     *
     * @return Language
     */
    public function addSubmission(\DOMJudgeBundle\Entity\Submission $submission)
    {
        $this->submissions[] = $submission;

        return $this;
    }

    /**
     * Remove submission
     *
     * @param \DOMJudgeBundle\Entity\Submission $submission
     */
    public function removeSubmission(\DOMJudgeBundle\Entity\Submission $submission)
    {
        $this->submissions->removeElement($submission);
    }

    /**
     * Get submissions
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getSubmissions()
    {
        return $this->submissions;
    }

    /**
     * Get the language for the ACE editor for this langauge
     * @return string
     */
    public function getAceLanguage()
    {
        switch ($this->getLangid()) {
            case 'c':
            case 'cpp':
            case 'cxx':
                return 'c_cpp';
            case 'pas':

webapp/src/DOMJudgeBundle/Form/Fls/SubmitProblemType.php
<?php declare(strict_types=1);

namespace DOMJudgeBundle\Form\Fls;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use DOMJudgeBundle\Entity\Language;
use DOMJudgeBundle\Entity\Problem;
use DOMJudgeBundle\Service\DOMJudgeService;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Form;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Context\ExecutionContextInterface;
use DOMJudgeBundle\Form\Type\BootstrapFileType;


class SubmitProblemType extends AbstractType
{
    /**
     * @var DOMJudgeService
     */
    protected $dj;

    /**
     * @var EntityManagerInterface
     */
    protected $em;

    public function __construct(DOMJudgeService $dj, EntityManagerInterface $em)
    {
        $this->dj = $dj;
        $this->em = $em;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $allowMultipleFiles = $this->dj->dbconfig_get('sourcefiles_limit', 100) > 1;

        $builder->add('fileInput', BootstrapFileType::class, [
            'label' => 'Source: ',
            'multiple' => $allowMultipleFiles,
            'required' => true]);
    }
}

webapp/src/DOMJudgeBundle/Controller/Teacher/InternalErrorController.php
<?php declare(strict_types=1);

namespace DOMJudgeBundle\Controller\Teacher;

use Doctrine\ORM\EntityManagerInterface;
use DOMJudgeBundle\Controller\BaseController;
use DOMJudgeBundle\Entity\ContestProblem;
use DOMJudgeBundle\Entity\InternalError;
use DOMJudgeBundle\Service\DOMJudgeService;
use DOMJudgeBundle\Utils\Utils;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\PropertyAccess\PropertyAccess;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/teacher/internal-errors")
 * @Security("has_role('ROLE_TEACHER')")
 */
class InternalErrorController extends BaseController
{
    /**
     * @var EntityManagerInterface
     */
    protected $em;

    /**
     * @var DOMJudgeService
     */
    protected $dj;

    public function __construct(EntityManagerInterface $em, DOMJudgeService $dj)
    {
        $this->em = $em;
        $this->dj = $dj;
    }

    /**
     * @Route("", name="teacher_internal_errors")
     */
    public function indexAction()
    {
        /** @var InternalError[] $internalErrors */
        $internalErrors = $this->em->createQueryBuilder()
            ->from('DOMJudgeBundle:InternalError', 'e')
            ->select('e')
            ->orderBy('e.status')
            ->addOrderBy('e.errorid')
            ->getQuery()->getResult();

        $table_fields = [
            'errorid' => ['title' => 'ID'],
            'judgingid' => ['title' => 'jid'],
            'description' => ['title' => 'description'],
            'time' => ['title' => 'time'],
            'status' => ['title' => 'status'],
        ];

        $propertyAccessor      = PropertyAccess::createPropertyAccessor();
        $internal_errors_table = [];
        foreach ($internalErrors as $internal) {
            $internalerrordata = [];
            // Get whatever fields we can from the problem object itself
            foreach ($table_fields as $k => $v) {
                if ($propertyAccessor->isReadable($internal, $k)) {
                    $internalerrordata[$k] = ['value' => $propertyAccessor->getValue($internal, $k)];
                }
            }

            $internalerrordata['time']['value'] = Utils::printtime($internalerrordata['time']['value'], '%F %T');

            // Save this to our list of rows
            $internal_errors_table[] = [
                'data' => $internalerrordata,
                'actions' => [],
                'link' => $this->generateUrl('teacher_internal_error', ['errorId' => $internal->getErrorid()]),
                'cssclass' => $internal->getStatus() === 'open' ? 'unseen' : 'disabled',
            ];
        }

        return $this->render('@DOMJudge/Fls/Teacher/internal_errors.html.twig', [
            'internal_errors' => $internal_errors_table,
            'table_fields' => $table_fields,
            'refresh' => [
                'after' => 15,
                'url' => $this->generateUrl('teacher_internal_errors'),
            ]
        ]);
    }

    /**
     * @Route("/{errorId}", methods={"GET"}, name="teacher_internal_error", requirements={"errorId": "\d+"})
     * @param int $errorId
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function viewAction(int $errorId)
    {
        /** @var InternalError $internalError */
        $internalError = $this->em->getRepository(InternalError::class)->find($errorId);
        if (!$internalError) {
            throw new NotFoundHttpException(sprintf('Internal Error with ID %s not found', $errorId));
        }

        $disabled     = $internalError->getDisabled();
        $affectedLink = $affectedText = null;
        switch ($disabled['kind']) {
            case 'problem':
                $affectedLink = $this->generateUrl('jury_problem', ['probId' => $disabled['probid']]);
                $idData       = ['cid' => $internalError->getCid(), 'probid' => $disabled['probid']];
                /** @var ContestProblem $problem */
                $problem      = $this->em->getRepository(ContestProblem::class)->find($idData);
                $affectedText = sprintf('%s - %s', $problem->getShortname(), $problem->getProblem()->getName());
                break;
            case 'judgehost':
                $affectedLink = $this->generateUrl('jury_judgehost', ['hostname' => $disabled['hostname']]);
                $affectedText = $disabled['hostname'];
                break;
            case 'language':
                $affectedLink = $this->generateUrl('jury_language', ['langId' => $disabled['langid']]);
                $affectedText = $disabled['langid'];
                break;
        }

        return $this->render('@DOMJudge/Fls/Teacher/internal_error.html.twig', [
            'internalError' => $internalError,
            'affectedLink' => $affectedLink,
            'affectedText' => $affectedText,
            'refresh' => [
                'after' => 15,
                'url' => $this->generateUrl('teacher_internal_error', ['errorId' => $internalError->getErrorid()]),
            ]
        ]);
    }

    /**
     * @Route(
     *     "/{errorId}/{action}",
     *     name="teacher_internal_error_handle",
     *     methods={"POST"},
     *     requirements={"errorId": "\d+", "action": "ignore|resolve"}
     * )
     * @param int    $errorId
     * @param string $action
     * @return \Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function handleAction(int $errorId, string $action)
    {
        /** @var InternalError $internalError */
        $internalError = $this->em->getRepository(InternalError::class)->find($errorId);
        $status        = $action === 'ignore' ? InternalError::STATUS_IGNROED : InternalError::STATUS_RESOLVED;
        $this->em->transactional(function () use ($internalError, $status) {
            $internalError->setStatus($status);
            if ($status === InternalError::STATUS_RESOLVED) {
                $this->dj->setInternalError($internalError->getDisabled(), $internalError->getContest(),
                                                         true);
                $this->dj->auditlog('internal_error', $internalError->getErrorid(),
                                                 sprintf('internal error: %s', $status));
            }
        });

        return $this->redirectToRoute('teacher_internal_error', ['errorId' => $internalError->getErrorid()]);
    }
}

webapp/src/DOMJudgeBundle/Resources/views/Fls/Teacher/delete.html.twig
{% extends "@DOMJudge/Fls/Teacher/base.html.twig" %}

{% block title %}Delete {{ type }} {{ primaryKey }} - "{{ description }}" - {{ parent() }}{% endblock %}


{% block content %}

    <h1>Delete {{ type }} {{ primaryKey }} - "{{ description }}"</h1>

    {% if isError %}
        <div class="alert alert-danger">
            <strong>Error: {{ messages.0 }}</strong>
        </div>
    {% else %}
        <div class="alert alert-warning">
            <form method="post">
                <p>You're about to delete {{ type }} {{ primaryKey }} "{{ description }}".</p>

                {% if messages is not empty %}
                    <p>
                        <strong>Warning, this will:</strong>
                    </p>
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}

                <p>Are you sure?</p>
                <hr>
                <a href="{{ redirectUrl }}" class="btn btn-secondary">Cancel</a>
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    {% endif %}

{% endblock %}

webapp/src/DOMJudgeBundle/Resources/views/Fls/Teacher/executable.html.twig
{% extends "@DOMJudge/Fls/Teacher/base.html.twig" %}
{% import _self as self %}
{% import "@DOMJudge/Fls/Teacher/teacher_macros.twig" as macros %}

{% block title %}Executable {{ executable.execid }} - {{ parent() }}{% endblock %}

{% block extrahead %}
    {{ parent() }}
    {{ macros.table_extrahead() }}
{% endblock %}

{% block content %}

    <h1>Executable {{ executable.execid }}</h1>

    <div class="row">
        <div class="col-lg-4">
            <table class="table table-sm table-striped">
                <tr>
                    <th>ID</th>
                    <td>{{ executable.execid }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ executable.description }}</td>
                </tr>
                <tr>
                    <th>MD5sum</th>
                    <td>{{ executable.md5sum }}</td>
                </tr>
                <tr>
                    <th>Type</th>
                    <td>{{ executable.type }}</td>
                </tr>
                <tr>
                    <th>Size</th>
                    <td>{{ executable.zipFileSize }} bytes</td>
                </tr>
                <tr>
                    <th>Content</th>
                    <td>
                        <a href="{{ path('teacher_executable_content', {'execId': executable.execid}) }}">
                            View file contents
                        </a>
                    </td>
                </tr>
                <tr>
                    <th>Used as {{ executable.type }} script</th>
                    <td>
                        {% set used = false %}
                        {% if executable.type == 'compare' and default_compare == executable.execid %}
                            <em>default compare</em>
                            {% set used = true %}
                        {% elseif executable.type == 'run' and default_run == executable.execid %}
                            <em>default run</em>
                            {% set used = true %}
                        {% endif %}
                        {% if executable.type == 'compare' %}
                            {% for problem in executable.problemsCompare %}
                                <a href="{{ path('teacher_problem', {'probId': problem.probid}) }}">
                                    p{{ problem.probid }}
                                </a>
                                {% set used = true %}
                            {% endfor %}
                        {% elseif executable.type == 'run' %}
                            {% for problem in executable.problemsRun %}
                                <a href="{{ path('teacher_problem', {'probId': problem.probid}) }}">
                                    p{{ problem.probid }}
                                </a>
                                {% set used = true %}
                            {% endfor %}
                        {% elseif executable.type == 'compile' %}
                            {% for language in executable.languages %}
                                <a href="{{ path('teacher_language', {'langId': language.langid,'cid':cid|default('')}) }}">
                                    {{ language.langid }}
                                </a>
                                {% set used = true %}
                            {% endfor %}
                        {% endif %}
                        {% if not used %}
                            <span class="nodata">none</span>
                        {% endif %}
                    </td>
                </tr>
            </table>
        </div>
    </div>

    <div class="mb-4">
        {%- if is_granted('ROLE_TEACHER') -%}
            <p>
                {{ button(path('teacher_executable_download', {'execId': executable.execid}), 'Download', 'secondary', 'file-download') }}
                {{ button(path('teacher_executable_edit', {'execId': executable.execid}), 'Edit', 'primary', 'edit') }}
                {{ button(path('teacher_executable_delete', {'execId': executable.execid}), 'Delete', 'danger', 'trash-alt', true) }}
            </p>
        {% endif %}
    </div>

{% endblock %}

webapp/src/DOMJudgeBundle/Resources/views/Fls/Teacher/executable_content.html.twig
{% extends "@DOMJudge/Fls/Teacher/base.html.twig" %}
{% import _self as self %}

{% block title %}View content of executable {{ executable.execid }} - {{ parent() }}{% endblock %}

{% block extrahead %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('js/ace/ace.js') }}" charset="utf-8"></script>
    <script type="text/javascript" src="{{ asset('js/ace/ext-modelist.js') }}" charset="utf-8"></script>
{% endblock %}

{% block content %}

    <h1>View content of executable {{ executable.execid }}</h1>

    {% if skippedBinary is not empty %}
        <div>
            Binary files:
            <ul>
                {% for file in skippedBinary %}
                    <li>{{ file }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    <ul class="nav nav-tabs source-tab-nav">
        {%- for idx, filename in filenames %}

            <li class="nav-item">
                <a class="nav-link {% if loop.first %}active{% endif %}" data-toggle="tab"
                   href="#source-{{ idx }}" role="tab">{{ filename }}</a>
            </li>
        {%- endfor %}

    </ul>
    <div class="tab-content source-tab">
        {%- for idx, filename in filenames %}
            <div class="tab-pane fade {% if loop.first %}show active{% endif %}" id="source-{{ idx }}"
                 role="tabpanel">
                <div class="mb-1">
                    <a class="btn btn-secondary btn-sm"
                       href="{{ path('teacher_executable_download_single', {execId: executable.execid, index: idx}) }}">
                        <i class="fas fa-download"></i> Download
                    </a>
                    <a class="btn btn-secondary btn-sm"
                       href="{{ path('teacher_executable_edit_files', {execId: executable.execid, index: idx}) }}">
                        <i class="fas fa-pencil-alt"></i> Edit
                    </a>
                </div>

                {{ files[idx] | codeEditor(idx, null, false, '', aceFilenames[idx]) }}
            </div>
        {%- endfor %}
    </div>

{% endblock %}

webapp/src/DOMJudgeBundle/Resources/views/Fls/Teacher/problem_add.html.twig
{% extends "@DOMJudge/Fls/Teacher/base.html.twig" %}
{% import _self as self %}
{% import "@DOMJudge/Fls/Teacher/teacher_macros.twig" as macros %}

{% block title %}Add problem - {{ parent() }}{% endblock %}
{% block extrahead %}
    {{ parent() }}
    {{ macros.select2_extrahead() }}
    {{ macros.jscolor_extrahead() }}
{% endblock %}

{% block content %}

    <h1>Add problem</h1>

    {% include '@DOMJudge/Fls/Teacher/partials/problem_form.html.twig' %}

{% endblock %}

webapp/src/DOMJudgeBundle/Resources/views/Fls/Teacher/submission_source.html.twig
{% extends "@DOMJudge/Fls/Teacher/base.html.twig" %}
{% import _self as self %}

{% block title %}Source s{{ submission.submitid }} - {{ parent() }}{% endblock %}

{% block extrahead %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('js/ace/ace.js') }}" charset="utf-8"></script>
{% endblock %}

{% block content %}

    <h1>
        Source code for submission
        <a href="{{ path('jury_submission', {submitId: submission.submitid}) }}">s{{ submission.submitid }}</a>
        {%- if submission.originalSubmission %}
            (resubmit of
            <a href="{{ path('jury_submission', {submitId: submission.originalSubmission.submitid}) }}">s{{ submission.originalSubmission.submitid }}</a>)
        {%- endif %}
        {% if submission.resubmissions is not empty %}
            (resubmitted as
            {%- for resubmission in submission.resubmissions %}
                <a href="{{ path('jury_submission', {submitId: resubmission.origsubmitid}) }}">s{{ resubmission.submitid }}</a>
                {%- if not loop.last -%},{%- endif -%}
            {%- endfor -%}
            )
        {% endif %}

    </h1>

    {%- if submission.entryPoint %}

        <p><b>Entry point</b>: {{ submission.entryPoint }}</p>
    {%- endif %}

    {%- if oldSubmission is not null %}

        <p><a href="#diff">Go to diff to previous submission</a></p>
    {%- endif %}

    {%- if submission.origsubmitid %}

        <p><a href="#origdiff">Go to diff to original submission</a></p>
    {%- endif %}

    <ul class="nav nav-tabs source-tab-nav">
        {%- for file in files %}

            <li class="nav-item">
                <a class="nav-link {% if loop.first %}active{% endif %}" data-toggle="tab"
                   href="#source-{{ file.rank }}" role="tab">{{ file.filename }}</a>
            </li>
        {%- endfor %}

    </ul>
    <div class="tab-content source-tab">
        {%- for file in files %}

            <div class="tab-pane fade {% if loop.first %}show active{% endif %}" id="source-{{ file.rank }}"
                 role="tabpanel">
                <div class="mb-1">
                    <a class="btn btn-secondary btn-sm"
                       href="{{ path('teacher_submission_source', {submission: submission.submitid, fetch: file.rank}) }}">
                        <i class="fas fa-download"></i> Download
                    </a>
                </div>

                {#{{ file.sourcecode | codeEditor(file.rank, submission.language.aceLanguage) }}#}
            </div>
        {%- endfor %}

    </div>

    {# {%- if oldSubmission is not null %}

        <h2 id="diff" class="mt-3">
            Diff to submission
            <a href="{{ path('jury_submission', {submitId: oldSubmission.submitid}) }}">
                s{{ oldSubmission.submitid }}
            </a>
        </h2>

        {%- include '@DOMJudge/jury/partials/submission_diff.html.twig' with {oldSubmission: oldSubmission, oldFiles: oldFiles, oldFileStats: oldFileStats} %}
    {%- endif %}

    {%- if originalSubmission is not null %}

        <h2 id="origdiff" class="mt-3">
            Diff to original submission
            <a href="{{ path('jury_submission', {submitId: originalSubmission.submitid}) }}">
                s{{ originalSubmission.submitid }}
            </a>
        </h2>

        {%- include '@DOMJudge/jury/partials/submission_diff.html.twig' with {oldSubmission: originalSubmission, oldFiles: originalFiles, oldFileStats: originalFileStats} %}
    {%- endif %} #}

{% endblock %}